---


- name: Allow Unix Agent - iptables
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "36602"
    jump: ACCEPT
    action: insert
  notify: "save iptables"

- name: Allow SNMP - iptables
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: "161"
    jump: ACCEPT
    action: insert
  notify: "save iptables"

- name: Allow SNMP - iptables
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: "162"
    jump: ACCEPT
    action: insert
  notify: "save iptables"

- name: Save existing iptables rule before start iptables service
  shell: "{{ iptables_save_command }}"  # noqa command-instead-of-shell
  when: __iptables_installed.changed | bool  # noqa no-handler


