---
- name: debian | Installing Debian Pre-Req Packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: '{{ observium_agent_debian_pakages }}'
  when: ansible_os_family == "Debian"

- name: Configure Firewall
  import_tasks: firewall.yml
- name: debian | Installing Debian Pre-Req Packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: '{{ observium_debian_pre_reqs }}'
- name: Force fail when svn user not defined
  fail:
    msg: "observium_commercial_svn_user variable is undefined, this means we cannot clone from observium SVN"
  when: not observium_commercial_svn_user | length > 0

- name: Force fail when svn password not defined
  fail:
    msg: "observium_commercial_svn_password variable is undefined, this means we cannot clone from observium SVN"
  when: not observium_commercial_svn_password | length > 0

- name: install-commercial | Downloading Observium to {{ observium_dl_dir }}
  subversion:
    repo: "{{ observium_commercial_svn_repo }}"
    dest: "{{ observium_base_dir }}"
    username: "{{ observium_commercial_svn_user }}"
    password: "{{ observium_commercial_svn_password }}"
    update: yes


- name: Upload Agent Installer
  template:
    src: "agent-installer.sh.j2"
    mode: "0777"
    dest: "{{ observium_base_dir }}/agent-installer.sh"

- name: Run Agent Installer
  ansible.builtin.shell: "{{ observium_base_dir }}/agent-installer.sh"
  args:
    executable: /bin/bash
    creates: "{{ observium_base_dir }}/.installed"

- name: Add Agent to Observium
  ansible.builtin.shell: |
     php /opt/observium/add_device.php {{ inventory_hostname }} {{ observium_agent_secret }}
  args:
    executable: bash
  delegate_to: "{{ ansible_user }}@{{ observium_host }}"
  delegate_facts: true
  become: true
  become_user: "root"
  tags: [ 'observium_agent:register' ]